### ISSUE TITLE
Add CORS support

### ISSUE THREAD

**Issue by shevron** [datopian/giftless#10]
As we want to allow browsers to directly talk to Giftless, we may want to consider adding CORS configuration support directly in Giftless. 

This should be optional and configurable. 

Alternatively, we should document a way to deploy Giftless so it is accessible via a proxy (e.g. nginx) in a way that handles CORS.

**Comment by shevron** [comment]
Now that Giftless supports generic WSGI middleware, I have been able to add CORS support without *any* code changes by doing:
```
pip install wsgi_cors_middleware
```
And then adding the following to the config YAML:
```yaml
MIDDLEWARE:
  - class: wsgi_cors_middleware:CorsMiddleware
    kwargs:
      origin: *
      headers: ['Content-type', 'Accept', 'Authorization']
      methods: ['GET', 'POST', 'PUT']
```
