### ISSUE TITLE
Please add curl as a dependency to allow health checks

### ISSUE THREAD

**Issue by piscis** [datopian/giftless#188]
Hi we would like to do health checks inside of the container with docker compose to see if the container is up and listening. I noticed that wget or curl are missing. It would be nice to have them backed into the image to make it possible to check if the service is up and running with a docker compose health check like this (not tested):

```yaml
...
healthcheck:
      test: ["CMD", "sh", "-c", "curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1:5000 | grep -q '404'"]
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 10s
...
```
