### ISSUE TITLE
Configuration: replace GCP_CREDENTIALS env var with a more convensional config method

### ISSUE THREAD

**Issue by shevron** [datopian/giftless#35]
Currently, the GCP storage backend looks for `GCP_CREDENTIALS` in the environment and uses it as a verbatim JSON string to use as credentials; This breaks our convnsion of passing in all configuration as arguments to the class constructor, hinders testing and complicates deployment by creating a "special case" for GCP. Also, it's not pretty 💩 

Let's replace it by adding the following config options to our standard config:

```yaml
TRANSFER_ADAPTERS:
  basic:
    factory: giftless.transfer.basic_external:factory
    options:
      storage_class: giftless.storage.google_cloud.GoogleCloudBlobStorage
      storage_options:
        account_key_file: /path/to/key/file.json  # Path to account key json file
        account_key_base64: ewogICJ0eXBlIjogInNlcnZp...2NvdW50LmNvbSIKfQo=  # Literal JSON string encoded with base64
```

This will allow users to provide the key *either* as a path to a local file or as an inline string containing the JSON encoded in base64. The reason for base64 encoding is to avoid the ugliness of escaped literal JSON inside a YAML string / env var. 

This will also allow users to specify the key as an environment variable by setting:

```bash
export GIFTLESS_TRANSFER_ADAPTERS_basic_options_storage_options_account_key_base64="ewogICJ0eXBlIjogInNlcnZp...2NvdW50LmNvbSIKfQo"
```

So it also handles the case of environments that don't support file uploading well correctly.
